import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  employees: [
    {
      EmployeeId: 1002,
      EmpName: "Jane Smith",
      Department: "Marketing",
      Salary: 60000,
      PhNumber: "555-5678",
      EmailId: "jane.smith@example.com",
      Address: "456 Elm St",
      State: "CA",
    },
    {
      EmployeeId: 1001,
      EmpName: "John Doe",
      Department: "HR",
      Salary: 50000,
      PhNumber: "555-1234",
      EmailId: "john.doe@example.com",
      Address: "123 Main St",
      State: "NY",
    },
    {
      EmployeeId: 1003,
      EmpName: "Michael Johnson",
      Department: "Finance",
      Salary: 55000,
      PhNumber: "555-9876",
      EmailId: "michael.johnson@example.com",
      Address: "789 Oak St",
      State: "TX",
    },
    {
      EmployeeId: 1005,
      EmpName: "David Garcia",
      Department: "Operations",
      Salary: 48000,
      PhNumber: "555-8765",
      EmailId: "david.garcia@example.com",
      Address: "202 Cedar St",
      State: "WA",
    },
    {
      EmployeeId: 1004,
      EmpName: "Emily Chen",
      Department: "IT",
      Salary: 65000,
      PhNumber: "555-5432",
      EmailId: "emily.chen@example.com",
      Address: "101 Maple St",
      State: "FL",
    },
    {
      EmployeeId: 1006,
      EmpName: "Anna Brown",
      Department: "Sales",
      Salary: 62000,
      PhNumber: "555-6789",
      EmailId: "anna.brown@example.com",
      Address: "333 Pine St",
      State: "NV",
    },
    {
      EmployeeId: 1007,
      EmpName: "Brian Wilson",
      Department: "Customer Support",
      Salary: 47000,
      PhNumber: "555-2345",
      EmailId: "brian.wilson@example.com",
      Address: "444 Birch St",
      State: "OR",
    },
    {
      EmployeeId: 1008,
      EmpName: "Carol Martinez",
      Department: "Legal",
      Salary: 70000,
      PhNumber: "555-3456",
      EmailId: "carol.martinez@example.com",
      Address: "555 Spruce St",
      State: "AZ",
    },
    {
      EmployeeId: 1009,
      EmpName: "Danielle Robinson",
      Department: "R&D",
      Salary: 72000,
      PhNumber: "555-4567",
      EmailId: "danielle.robinson@example.com",
      Address: "666 Aspen St",
      State: "CO",
    },
    {
      EmployeeId: 1010,
      EmpName: "Edward Lee",
      Department: "Design",
      Salary: 69000,
      PhNumber: "555-5678",
      EmailId: "edward.lee@example.com",
      Address: "777 Walnut St",
      State: "UT",
    },
    {
      EmployeeId: 1011,
      EmpName: "Fiona Clark",
      Department: "Admin",
      Salary: 51000,
      PhNumber: "555-6789",
      EmailId: "fiona.clark@example.com",
      Address: "888 Fir St",
      State: "IL",
    },
    {
      EmployeeId: 1012,
      EmpName: "George Lewis",
      Department: "Procurement",
      Salary: 58000,
      PhNumber: "555-7890",
      EmailId: "george.lewis@example.com",
      Address: "999 Palm St",
      State: "GA",
    },
    {
      EmployeeId: 1013,
      EmpName: "Hannah Walker",
      Department: "Facilities",
      Salary: 49000,
      PhNumber: "555-8901",
      EmailId: "hannah.walker@example.com",
      Address: "1010 Cedar St",
      State: "NC",
    },
    {
      EmployeeId: 1014,
      EmpName: "Ian Hall",
      Department: "Security",
      Salary: 52000,
      PhNumber: "555-9012",
      EmailId: "ian.hall@example.com",
      Address: "1111 Poplar St",
      State: "VA",
    },
    {
      EmployeeId: 1015,
      EmpName: "Julia Young",
      Department: "Public Relations",
      Salary: 63000,
      PhNumber: "555-0123",
      EmailId: "julia.young@example.com",
      Address: "1212 Magnolia St",
      State: "TN",
    },
    {
      EmployeeId: 1016,
      EmpName: "Kyle King",
      Department: "Logistics",
      Salary: 54000,
      PhNumber: "555-1234",
      EmailId: "kyle.king@example.com",
      Address: "1313 Alder St",
      State: "OH",
    },
    {
      EmployeeId: 1017,
      EmpName: "Laura Scott",
      Department: "Production",
      Salary: 61000,
      PhNumber: "555-2345",
      EmailId: "laura.scott@example.com",
      Address: "1414 Chestnut St",
      State: "MO",
    },
    {
      EmployeeId: 1018,
      EmpName: "Mark Hernandez",
      Department: "Maintenance",
      Salary: 53000,
      PhNumber: "555-3456",
      EmailId: "mark.hernandez@example.com",
      Address: "1515 Sequoia St",
      State: "MI",
    },
    {
      EmployeeId: 1019,
      EmpName: "Nina Adams",
      Department: "Strategy",
      Salary: 75000,
      PhNumber: "555-4567",
      EmailId: "nina.adams@example.com",
      Address: "1616 Redwood St",
      State: "PA",
    },
    {
      EmployeeId: 1020,
      EmpName: "Oscar Ramirez",
      Department: "Development",
      Salary: 68000,
      PhNumber: "555-5678",
      EmailId: "oscar.ramirez@example.com",
      Address: "1717 Cypress St",
      State: "MD",
    },
    {
      EmployeeId: 1021,
      EmpName: "Paula Campbell",
      Department: "Analytics",
      Salary: 64000,
      PhNumber: "555-6789",
      EmailId: "paula.campbell@example.com",
      Address: "1818 Sycamore St",
      State: "WI",
    },
    {
      EmployeeId: 1022,
      EmpName: "Quentin Mitchell",
      Department: "Engineering",
      Salary: 72000,
      PhNumber: "555-7890",
      EmailId: "quentin.mitchell@example.com",
      Address: "1919 Willow St",
      State: "MN",
    },
    {
      EmployeeId: 1023,
      EmpName: "Rachel Cooper",
      Department: "Quality",
      Salary: 58000,
      PhNumber: "555-8901",
      EmailId: "rachel.cooper@example.com",
      Address: "2020 Hickory St",
      State: "IN",
    },
    {
      EmployeeId: 1024,
      EmpName: "Sam Peterson",
      Department: "Research",
      Salary: 67000,
      PhNumber: "555-9012",
      EmailId: "sam.peterson@example.com",
      Address: "2121 Dogwood St",
      State: "IA",
    },
    {
      EmployeeId: 1025,
      EmpName: "Tina Bailey",
      Department: "Training",
      Salary: 56000,
      PhNumber: "555-0123",
      EmailId: "tina.bailey@example.com",
      Address: "2222 Juniper St",
      State: "KY",
    },
    {
      EmployeeId: 1026,
      EmpName: "Uma Parker",
      Department: "Consulting",
      Salary: 71000,
      PhNumber: "555-1234",
      EmailId: "uma.parker@example.com",
      Address: "2323 Elmwood St",
      State: "OK",
    },
    {
      EmployeeId: 1027,
      EmpName: "Victor Morris",
      Department: "Communications",
      Salary: 59000,
      PhNumber: "555-2345",
      EmailId: "victor.morris@example.com",
      Address: "2424 Cottonwood St",
      State: "KS",
    },
    {
      EmployeeId: 1028,
      EmpName: "Wendy Bell",
      Department: "Legal",
      Salary: 73000,
      PhNumber: "555-3456",
      EmailId: "wendy.bell@example.com",
      Address: "2525 Aspenwood St",
      State: "MS",
    },
    {
      EmployeeId: 1029,
      EmpName: "Xavier Russell",
      Department: "Risk Management",
      Salary: 66000,
      PhNumber: "555-4567",
      EmailId: "xavier.russell@example.com",
      Address: "2626 Redwood St",
      State: "LA",
    },
    {
      EmployeeId: 1030,
      EmpName: "Yvonne Scott",
      Department: "Compliance",
      Salary: 64000,
      PhNumber: "555-5678",
      EmailId: "yvonne.scott@example.com",
      Address: "2727 Cedarwood St",
      State: "AR",
    },
    {
      EmployeeId: 1031,
      EmpName: "Zachary Reed",
      Department: "Innovation",
      Salary: 78000,
      PhNumber: "555-6789",
      EmailId: "zachary.reed@example.com",
      Address: "2828 Ironwood St",
      State: "NM",
    },
  ],
};

const employeeSlice = createSlice({
  name: "employee",
  initialState,
  reducers: {
    addEmployee: (state, action) => {
      state.employees.unshift(action.payload);
    },
    removeEmployee: (state, action) => {
      state.employees = state.employees.filter(
        (emp) => emp.EmployeeId !== action.payload
      );
    },
  },
});

export const { addEmployee, removeEmployee } = employeeSlice.actions;
export default employeeSlice.reducer;
